from __future__ import annotations

import random
from typing import List, Dict, Set

from dataclasses import dataclass

from Options import Range, OptionList, DefaultOnToggle

from ..game import Game
from ..game_objective_template import GameObjectiveTemplate

from ..enums import KeymastersKeepGamePlatforms


# Option Dataclass
@dataclass
class ArchipelagourmetArchipelagoOptions:
    archipelagourmet_recipes: ArchipelagourmetRecipes
    archipelagourmet_takeaway_options: ArchipelagourmetTakeawayOptions
    archipelagourmet_restaurant_options: ArchipelagourmetRestaurantOptions
    archipelagourmet_include_red_meat_options: ArchipelagourmetIngredientsIncludeRedMeatOptions
    archipelagourmet_include_poultry_options: ArchipelagourmetIngredientsIncludePoultryOptions
    archipelagourmet_include_seafood_options: ArchipelagourmetIngredientsIncludeSeafoodOptions
    archipelagourmet_include_nonvegan_options: ArchipelagourmetIngredientsIncludeNonVeganOptions
    archipelagourmet_custom_ingredients_to_include: ArchipelagourmetCustomIngredientsToInclude
    archipelagourmet_ingredients_to_exclude: ArchipelagourmetIngredientsToExclude
    archipelagourmet_minimum_ingredient_count: ArchipelagourmetMinimumIngredientCount
    archipelagourmet_maximum_ingredient_count: ArchipelagourmetMaximumIngredientCount
    archipelagourmet_recipes_weight: ArchipelagourmetRecipesWeight
    archipelagourmet_takeaway_options_weight: ArchipelagourmetTakeawayOptionsWeight
    archipelagourmet_restaurant_options_weight: ArchipelagourmetRestaurantOptionsWeight
    archipelagourmet_ingredients_weight: ArchipelagourmetIngredientsOptionsWeight

# Main Class
class ArchipelagourmetGame(Game):
    name = "Archipelagourmet"
    platform = KeymastersKeepGamePlatforms.META

    is_adult_only_or_unrated = False

    options_cls = ArchipelagourmetArchipelagoOptions

    # Main Objectives
    def game_objective_templates(self) -> List[GameObjectiveTemplate]:
        game_objective_templates: List[GameObjectiveTemplate] = []
        
        min_ingredients = self.archipelago_options.archipelagourmet_minimum_ingredient_count.value
        max_ingredients = self.archipelago_options.archipelagourmet_maximum_ingredient_count.value
        ingredient_range_breadth = max_ingredients - min_ingredients + 1
        
        # Create an objective for each possible ingredient count
        for ingredient_count in range(min_ingredients, max_ingredients + 1):
            game_objective_templates.append(
                GameObjectiveTemplate(
                    label="Prepare a meal using the following ingredients: INGREDIENTS",
                    data={
                        "INGREDIENTS": (self.ingredients, ingredient_count),
                    },
                    is_time_consuming=False,
                    is_difficult=False,
                    weight=self.ingredients_weight,
                ),
            )

        if self.recipes:
            game_objective_templates.append(
                GameObjectiveTemplate(
                    label="Make and eat the following dish: RECIPES",
                    data={
                        "RECIPES": (self.recipes, 1),
                    },
                    is_time_consuming=False,
                    is_difficult=False,
                    weight=self.recipes_weight * ingredient_range_breadth,
                ),
            )

        if self.takeaways:
            game_objective_templates.append(
                GameObjectiveTemplate(
                    label="Order the following takeaway option: TAKEAWAYS",
                    data={
                        "TAKEAWAYS": (self.takeaways, 1),
                    },
                    is_time_consuming=False,
                    is_difficult=False,
                    weight=self.takeaways_weight * ingredient_range_breadth,
                ),
            )

        if self.restaurants:
            game_objective_templates.append(
                GameObjectiveTemplate(
                    label="Order the following restaurant option: RESTAURANTS",
                    data={
                        "RESTAURANTS": (self.restaurants, 1),
                    },
                    is_time_consuming=False,
                    is_difficult=False,
                    weight=self.restaurants_weight * ingredient_range_breadth,
                ),
            )
        
        return game_objective_templates

    @property
    def recipes_weight(self) -> int:
        return self.archipelago_options.archipelagourmet_recipes_weight.value
    
    @property
    def takeaways_weight(self) -> int:
        return self.archipelago_options.archipelagourmet_takeaway_options_weight.value
    
    @property
    def restaurants_weight(self) -> int:
        return self.archipelago_options.archipelagourmet_restaurant_options_weight.value

    @property
    def ingredients_weight(self) -> int:
        return self.archipelago_options.archipelagourmet_ingredients_weight.value

    def recipes(self) -> List[str]:
        recipes: List[str] = list(self.archipelago_options.archipelagourmet_recipes.value)
        return sorted(recipes)
    
    def takeaways(self) -> List[str]:
        takeaways: List[str] = list(self.archipelago_options.archipelagourmet_takeaway_options.value)
        return sorted(takeaways)
    
    def restaurants(self) -> List[str]:
        restaurants: List[str] = list(self.archipelago_options.archipelagourmet_restaurant_options.value)
        return sorted(restaurants)

    @property
    def include_red_meat_ingredients(self) -> bool:
        return bool(self.archipelago_options.archipelagourmet_include_red_meat_options.value)

    @property
    def include_poultry_ingredients(self) -> bool:
        return bool(self.archipelago_options.archipelagourmet_include_poultry_options.value)
    
    @property
    def include_seafood_ingredients(self) -> bool:
        return bool(self.archipelago_options.archipelagourmet_include_seafood_options.value)
    
    @property
    def include_nonvegan_ingredients(self) -> bool:
        return bool(self.archipelago_options.archipelagourmet_include_nonvegan_options.value)

    def ingredients_base(self) -> List[str]:
        return [
            "00 flour",
            "acidulated water",
            "ackee",
            "acornn squash",
            "aduki beans",
            "agar-agar",
            "agave syrup",
            "ajwain",
            "ale",
            "aleppo pepper",
            "alfalfa sprouts",
            "allspice",
            "almond",
            "almond butter",
            "almond essence",
            "almond extract",
            "almond milk",
            "amaranth",
            "amaretto",
            "amchoor",
            "angelica",
            "angostura bitters",
            "anise",
            "annatto",
            "apple",
            "apple chuntney",
            "apple juice",
            "apple sauce",
            "apricot",
            "apricot jam",
            "aquafaba",
            "arborio rice",
            "argan oil",
            "arrowroot",
            "artichoke",
            "asafoetida",
            "asparagus",
            "aubergine",
            "avocado",
            "baby corn",
            "bagel",
            "baguette",
            "baharat",
            "baked beans",
            "baking powder",
            "balsamic vinegar",
            "bamboo shoots",
            "banana",
            "banana bread",
            "bao buns",
            "bara brith",
            "barbecue sauce",
            "barley",
            "basil",
            "basmati rice",
            "bay boletes",
            "bay leaf",
            "beans",
            "beansprouts",
            "beef tomato",
            "beer",
            "beetroot",
            "berry",
            "betel leaves",
            "bicarbonate of soda",
            "bitter gourd",
            "bilberries",
            "bird's-eye chillies",
            "biscuits",
            "black bean",
            "black bean sauce",
            "black cardamom",
            "black eyed beans",
            "black pepper",
            "black salsify",
            "black salt",
            "black sesame seeds",
            "blackberry",
            "blackcurrant",
            "blackcurrant juice drink",
            "blood orange",
            "blueberry",
            "bok choi",
            "Bombay mix",
            "borage",
            "borlotti beans",
            "bottle gourd",
            "bouquet garni",
            "Bramley apple",
            "bran",
            "brandy",
            "brazil nut",
            "bread",
            "bread roll",
            "breadcrumbs",
            "breadfruit",
            "breadsticks",
            "broad beans",
            "broccoli",
            "broth",
            "brown bread",
            "brown lentil",
            "brown rice",
            "brown sauce",
            "brown sugar",
            "brussels sprouts",
            "buckwheat",
            "buckwheat flour",
            "bulgur wheat",
            "butter beans",
            "butterhead lettuce",
            "butternut squash",
            "cabbage",
            "calasparra rice",
            "calvados",
            "campagne loaf",
            "candied peel",
            "cannellini beans",
            "cannelloni",
            "cape gooseberries",
            "capers",
            "capsicum",
            "caramel",
            "caraway seeds",
            "cardamom",
            "carob",
            "carrageen moss",
            "carrot",
            "cashew",
            "cashew milk",
            "cassava",
            "cassia bark",
            "castor sugar",
            "cauliflower",
            "cava",
            "cavolo nero",
            "cayenne pepper",
            "celeriac",
            "celery",
            "celery seeds",
            "chaat masala",
            "chamomile",
            "champagne",
            "chana dal",
            "chanterelle mushrooms",
            "chapati flour",
            "chapatis",
            "chard",
            "Charlotte potato",
            "chayote",
            "cherry",
            "cherry brandy",
            "cherry tomatoes",
            "chervil",
            "chestnut",
            "chestnut mushrooms",
            "chia seeds",
            "chickpea",
            "chickpea flour",
            "chicory",
            "chilli",
            "chilli flakes",
            "chilli oil",
            "chilli paste",
            "chilli powder",
            "chilli sauce",
            "chilli-lime seasoning",
            "Chinese cabbage",
            "Chinese mushrooms",
            "Chinese pancake",
            "chipotle",
            "chips",
            "chiramoya",
            "chives",
            "chocolate",
            "chopped tomatoes",
            "Christmas pudding",
            "chutney",
            "ciabatta",
            "cider",
            "cinnamon",
            "citrus fruit",
            "citrus ponzu",
            "clementine",
            "clover",
            "cloves",
            "cobnut",
            "cocoa butter",
            "cocoa powder",
            "coconut",
            "coconut cream",
            "coconut flour",
            "coconut milk",
            "coconut oil",
            "coffee",
            "coffee beans",
            "coffee essence",
            "coffee granules",
            "coffee liqueur",
            "cognac",
            "cola",
            "compôte",
            "cordial",
            "coriander",
            "coriander cress",
            "coriander seeds",
            "corn meal",
            "corn oil",
            "corn syrup",
            "cornflour",
            "cornichon",
            "cos lettuce",
            "corn tortilla",
            "coulis",
            "courgette",
            "court bouillon",
            "couscous",
            "crab apple",
            "crackers",
            "cranberry",
            "cranberry juice",
            "cranberry sauce",
            "cream of tartar",
            "cream soda",
            "creamed coconut",
            "cress",
            "crispbread",
            "crisps",
            "crispy onions",
            "crostini",
            "croûtons",
            "crudités",
            "crumble",
            "crystallised ginger",
            "cucumber",
            "Cumberland sauce",
            "cumin",
            "curacao",
            "curly kale",
            "currant bread",
            "currants",
            "curry",
            "curry leaves",
            "curry paste",
            "curry powder",
            "daikon",
            "dal",
            "damsons",
            "dandelion",
            "dark chocolate",
            "dashi",
            "date",
            "demerara sugar",
            "demi-glace sauce",
            "dessicated coconut",
            "Desirée potato",
            "digestive biscuit",
            "Dijon mustard",
            "dill",
            "dim sum wrappers",
            "dragon fruit",
            "dried apricots",
            "dried cherries",
            "dried chilli",
            "dried fruit",
            "dried mixed fruit",
            "dried mixed herbs",
            "dry sherry",
            "dumplings",
            "edamame",
            "elderberries",
            "elderflower",
            "English muffin",
            "English mustard",
            "exotic fruit",
            "falafel",
            "farfalle",
            "fat",
            "fennel",
            "fennel seeds",
            "fenugreek",
            "fettucine",
            "field mushroom",
            "fig",
            "filo pastry",
            "fines herbes",
            "five-spice powder",
            "flageolet beans",
            "flaked almonds",
            "flapjacks",
            "flatbread",
            "flaxseed",
            "fleur de sel",
            "flour",
            "flour tortilla",
            "floury potato",
            "focaccia",
            "fondant icing",
            "fondant potatoes",
            "food colouring",
            "forced rhubarb",
            "fortified wine",
            "freekeh",
            "French beans",
            "French bread",
            "French dressing",
            "fresh coriander",
            "frosting",
            "fruit",
            "fruit brandy",
            "fruit juice",
            "fruit salad",
            "fruit soda",
            "fusilli",
            "galangal",
            "garam masala",
            "gari",
            "garlic",
            "garlic bread",
            "gherkin",
            "gin",
            "ginger",
            "ginger ale",
            "ginger beer",
            "ginger biscuit",
            "glacé cherries",
            "glass bean noodles",
            "globe artichoke",
            "glucose",
            "gluten-free flour",
            "gnocchi",
            "gochugaru",
            "gochujang",
            "goji berries",
            "golden syrup",
            "gooseberry",
            "gourd",
            "grains",
            "gram flour",
            "granola",
            "grape juice",
            "grapefruit",
            "grapefruit juice",
            "grapes",
            "grapeseed oil",
            "gravy",
            "gravy browning",
            "green banana",
            "green beans",
            "green cabbage",
            "green lentil",
            "green tea",
            "greengages",
            "ground almonds",
            "ground ginger",
            "guacamole",
            "guava",
            "habañero chilli",
            "haricot beans",
            "harissa",
            "hazelnut",
            "hazelnut oil",
            "hearts of palm",
            "hemp milk",
            "herbal liqueur",
            "herbal tea",
            "herbes de Provence",
            "herbs",
            "hoisin sauce",
            "hominy",
            "honeycomb",
            "horseradish",
            "hummus",
            "hunza apricots",
            "iceberg lettuce",
            "icing",
            "icing sugar",
            "Irish stout",
            "ivy gourd",
            "jacket potato",
            "jackfruit",
            "jaggery",
            "jalapeño chilli",
            "jam",
            "January king cabbage",
            "Japanese pumpkin",
            "jasmine rice",
            "jerk seasoning",
            "Jersey royal potatoes",
            "Jerusalem artichoke",
            "jujube",
            "juniper berries",
            "jus",
            "kale",
            "ketjap manis",
            "kidney beans",
            "kimchi",
            "King Edward potatoes",
            "kirsch",
            "kiwi fruit",
            "kohlrabi",
            "kumquat",
            "lager",
            "lamb's lettuce",
            "lasagne sheets",
            "laverbread",
            "leek",
            "lemon",
            "lemon balm",
            "lemon juice",
            "lemonade",
            "lemongrass",
            "lentil soup",
            "lentils",
            "lettuce",
            "lime",
            "lime cordial",
            "lime juice",
            "lime leaves",
            "lime pickle",
            "lingonberry",
            "linguine",
            "liqueur",
            "liquorice",
            "little gem lettuce",
            "loaf cake",
            "loganberry",
            "long-grain rice",
            "lovage",
            "low-calorie sweetener",
            "lychee",
            "macadamia",
            "macaroni",
            "mace",
            "madeira",
            "maize",
            "malted grain bread",
            "mandarin",
            "mangetout",
            "mango",
            "mango chutney",
            "mango juice",
            "mango pickle",
            "mangosteen",
            "maple syrup",
            "margarine",
            "marjoram",
            "marmalade",
            "marrow",
            "marrowfat peas",
            "marsala wine",
            "marzipan",
            "mashed potato",
            "matzo",
            "medlars",
            "melon",
            "melon seeds",
            "membrillo",
            "menma",
            "mesclun",
            "millet",
            "millet flour",
            "mince pies",
            "mincemeat",
            "mint",
            "mint sauce",
            "mirepoix",
            "mirin",
            "miso",
            "mixed berries",
            "mixed dried beans",
            "mixed nuts",
            "mixed spice",
            "mixed spices",
            "molasses",
            "monk's beard",
            "morel",
            "muesli",
            "mulberries",
            "mulled wine",
            "mung beans",
            "mung dal",
            "muscovado sugar",
            "mushroom",
            "mustard",
            "mustard cress",
            "mustard leaves",
            "mustard oil",
            "mustard powder",
            "mustard seeds",
            "naan bread",
            "nachos",
            "nashi",
            "nasturtium",
            "nectarine",
            "nettle",
            "new potatoes",
            "nibbed almonds",
            "nigella seeds",
            "non-dairy yoghurt",
            "noodle soup",
            "noodles",
            "nori",
            "nut",
            "nutmeg",
            "nutritional yeast",
            "oak leaf lettuce",
            "oat cream",
            "oat milk",
            "oatcakes",
            "oatmeal",
            "oats",
            "oil",
            "okra",
            "olive",
            "olive oil",
            "onion",
            "orange",
            "orange juice",
            "orange liqueur",
            "oregano",
            "orzo",
            "ouzo",
            "oyster mushrooms",
            "padron peppers",
            "paella",
            "pak choi",
            "palm sugar",
            "panch phoron",
            "pandan leaves",
            "panko breadcrumbs",
            "papaya",
            "pappardelle",
            "paprika",
            "parsley",
            "parsnip",
            "passata",
            "passion fruit",
            "passion fruit juice",
            "pasta",
            "pasta sauce",
            "pastry",
            "pasty",
            "pâté",
            "paw-paw",
            "pea milk",
            "pea shoots",
            "peach",
            "peanut butter",
            "peanut oil",
            "peanuts",
            "pear",
            "pearl barley",
            "peas",
            "pecan",
            "pectin",
            "peel",
            "penne",
            "pepper",
            "peppercorn",
            "perry",
            "pesto",
            "piccalilli",
            "pickle",
            "pickled ginger",
            "pickled onion",
            "pie",
            "pigeon peas",
            "pine nut",
            "pineapple",
            "pineapple juice",
            "Pink Fir Apple potatoes",
            "pink peppercorns",
            "pinto beans",
            "piri-piri",
            "pistachio",
            "pitta bread",
            "pizza",
            "plain flour",
            "plant-based milk",
            "plantain",
            "plum",
            "polenta",
            "pomegranate",
            "pomegranate juice",
            "pomegranate molasses",
            "pomelo",
            "popcorn",
            "poppy seeds",
            "porcini",
            "porridge",
            "port",
            "portobello mushroom",
            "potato",
            "potato rösti",
            "potato wedges",
            "praline",
            "preserved lemons",
            "preserves",
            "pretzels",
            "prune",
            "prune juice",
            "pudding rice",
            "puff pastry",
            "pumpernickel bread",
            "pumpkin",
            "pumpkin seed",
            "purple sprouting broccoli",
            "purslane",
            "puy lentils",
            "quatre-épices",
            "quince",
            "quinoa",
            "Quorn",
            "radicchio",
            "radish",
            "rainbow chard",
            "raisins",
            "ramen noodles",
            "rapeseed oil",
            "ras-el-hanout",
            "raspberry",
            "raspberry jam",
            "ratatouille",
            "red cabbage",
            "red lentil",
            "red onion",
            "red rice",
            "red wine",
            "red wine vinegar",
            "redcurrant",
            "redcurrant jelly",
            "relish",
            "rhubarb",
            "rice",
            "rice cake",
            "rice cream",
            "rice flour",
            "rice milk",
            "rice noodles",
            "rice paper wrappers",
            "rice vinegar",
            "rice wine",
            "ridged gourd",
            "rigatoni",
            "risotto",
            "risotto rice",
            "roast potatoes",
            "roasted vegetables",
            "rock salt",
            "rocket",
            "romanesco cauliflower",
            "root beer",
            "root vegetable",
            "rose wine",
            "rosehip syrup",
            "rosemary",
            "rosewater",
            "rouille",
            "rum",
            "runner beans",
            "rye bread",
            "rye flour",
            "safflower oil",
            "saffron",
            "sage",
            "sago",
            "sake",
            "salad",
            "salad leaves",
            "salsa",
            "sambuca",
            "samosa",
            "samphire",
            "sandwich",
            "satay",
            "satsuma",
            "sauce",
            "sauerkraut",
            "savory",
            "Savoy cabbage",
            "scotch bonnet chilli",
            "sea salt",
            "seasoning",
            "seaweed",
            "seeds",
            "self-raising flour",
            "semolina",
            "sesame oil",
            "sesame seeds",
            "sev",
            "Seville orange",
            "shallot",
            "sharon fruit",
            "sherry",
            "sherry vinegar",
            "shichimi togarashi",
            "shiitake mushrooms",
            "shortcrust pastry",
            "Sichuan pepper",
            "sloe",
            "sloe gin",
            "smoked paprika",
            "snake gourd",
            "soba noodles",
            "soda bread",
            "soda water",
            "sorbet",
            "sorrel",
            "soup",
            "sourdough bread",
            "soy cream",
            "soy sauce",
            "soy yoghurt",
            "soya beans",
            "soya flour",
            "soya milk",
            "soya oil",
            "spaghetti",
            "spaghetti squash",
            "sparkling wine",
            "spelt",
            "spelt flour",
            "spices",
            "spinach",
            "split peas",
            "spring greens",
            "spring onion",
            "spring roll wrappers",
            "squash",
            "sriracha",
            "star anise",
            "starfruit",
            "stem ginger",
            "stew",
            "stir-fry",
            "stock",
            "stone fruit",
            "stout",
            "straw mushroom",
            "strawberry",
            "strawberry jam",
            "Strega liqueur",
            "strong white flour",
            "stuffing",
            "sucralose",
            "sugar",
            "sugar snap peas",
            "sultanas",
            "sumac",
            "summer cabbage",
            "summer fruit",
            "sun-dried tomatoes",
            "sunflower oil",
            "sunflower seed",
            "sushi rice",
            "swede",
            "sweet potato",
            "sweet sherry",
            "sweetcorn",
            "sweets",
            "Swiss chard",
            "syrup",
            "tabasco",
            "taco",
            "tagliatelle",
            "tahini",
            "tamari",
            "tamarillo",
            "tamarind",
            "tamgerine",
            "tapenade",
            "tapioca",
            "tapioca flour",
            "taro",
            "tarragon",
            "tayberry",
            "tea",
            "tempeh",
            "tempura",
            "tequila",
            "teriyaki",
            "teriyaki sauce",
            "textured soy",
            "textured vegetable protein",
            "Thai basil",
            "Thai curry",
            "tinned tomatoes",
            "tofu",
            "tomatillo",
            "tomato",
            "tomato chutney",
            "tomato juice",
            "tomato ketchup",
            "tomato purée",
            "tomato soup",
            "tonic",
            "tonkatsu sauce",
            "tortellini",
            "tostada",
            "toyomansi",
            "treacle",
            "truffle",
            "truffle oil",
            "Turkish delight",
            "turmeric",
            "turnip",
            "udon noodles",
            "unleavened bread",
            "urid dal",
            "vanilla essence",
            "vanilla extract",
            "vanilla pod",
            "vegan cheese",
            "vegan spread",
            "vegetable oil",
            "vegetable shortening",
            "vegetable stock",
            "vegetables",
            "vegetarian haggis",
            "vegetarian mince",
            "vegetarian sausage",
            "veggie burger",
            "verjus",
            "vermicelli (pasta)",
            "vermicelli (rice)",
            "vermouth",
            "vine leaves",
            "vinegar",
            "vital wheat gluten",
            "vodka",
            "wakame",
            "walnut",
            "walnut oil",
            "wasabi",
            "water chestnut",
            "watercress",
            "watermelon",
            "wax gourd",
            "waxy potato",
            "wheatberries",
            "wheatgerm",
            "whisky",
            "whisky liqueur",
            "white bread",
            "white cabbage",
            "white pepper",
            "white wine",
            "white wine vinegar",
            "whitecurrant",
            "whole wheat pasta",
            "wholegrain mustard",
            "wholemeal bread",
            "wholemeal flour",
            "wild garlic",
            "wild mushrooms",
            "wild rice",
            "wine",
            "wraps",
            "yam",
            "yeast",
            "yeast extract",
            "yeast flakes",
            "yellow lentil",
            "yuzu",
            "yuzu juice",
            "zest",
        ]

    def ingredients_red_meat(self) -> List[str]:
        return [
            "bacon",
            "beef",
            "beef burger",
            "beef consommé",
            "beef dripping",
            "beef heart",
            "beef mince",
            "beef ribs",
            "beef rump",
            "beef sausage",
            "beef stock",
            "best end of lamb",
            "black pudding",
            "boar",
            "bone marrow",
            "braising steak",
            "Bratwurst",
            "bresaola",
            "brisket",
            "calves' kidney",
            "calves' liver",
            "caul fat",
            "charcuterie",
            "chorizo",
            "chuck and blade",
            "chump",
            "collar",
            "corned beef",
            "fillet of beef",
            "flank",
            "frankfurter",
            "gammon",
            "gelatine",
            "goat",
            "haggis",
            "ham",
            "hare",
            "hogget",
            "jelly",
            "kabana",
            "kidney",
            "lamb",
            "lamb breast",
            "lamb burger",
            "lamb chop",
            "lamb fillet",
            "lamb heart",
            "lamb kidney",
            "lamb liver",
            "lamb loin",
            "lamb mince",
            "lamb neck",
            "lamb rump",
            "lamb shank",
            "lamb shoulder",
            "lamb stock",
            "lard",
            "lardons",
            "leftover turkey",
            "leg of lamb",
            "liver",
            "marshmallow",
            "meat",
            "meatballs",
            "mince",
            "mortadella",
            "mutton",
            "'nduja",
            "offal",
            "ox kidney",
            "oxtail",
            "pancetta",
            "Parma ham",
            "pastrami",
            "pepperoni",
            "pig cheeks",
            "pig heart",
            "pork",
            "pork belly",
            "pork burger",
            "pork chop",
            "pork escalope",
            "pork fillet",
            "pork leg",
            "pork loin",
            "pork mince",
            "pork ribs",
            "pork sausages",
            "pork shoulder",
            "pork spare rib",
            "prosciutto",
            "pulled pork",
            "rabbit",
            "rack of lamb",
            "rennet",
            "rib of beef",
            "roast beef",
            "roast lamb",
            "roast pork",
            "rump",
            "salami",
            "saucisson",
            "sausage",
            "scrag",
            "Serrano ham",
            "shin",
            "silverside",
            "sirloin",
            "steak",
            "stewing lamb",
            "suet",
            "sweetbread",
            "T-bone steak",
            "tongue",
            "topside",
            "tripe",
            "veal",
            "veal escalope",
            "venison",
            "wild boar",
        ]

    def ingredients_poultry(self) -> List[str]:
        return [
            "Barbary duck",
            "chicken",
            "chicken breast",
            "chicken goujons",
            "chicken heart",
            "chicken leg",
            "chicken liver",
            "chicken mince",
            "chicken stock",
            "chicken thigh",
            "chicken wing",
            "duck",
            "duck confit",
            "duck fat",
            "duck liver",
            "foie gras",
            "game",
            "giblets",
            "goose",
            "goose fat",
            "goose liver",
            "grouse",
            "guinea fowl",
            "partridge",
            "pheasant",
            "pigeon",
            "poultry",
            "poussin",
            "quail",
            "roast chicken",
            "roast turkey",
            "snipe",
            "turkey",
            "turkey breast",
            "turkey crown",
            "turkey escalope",
            "turkey mince",
            "wild duck",
            "wood pigeon",
            "woodcock",
        ]

    def ingredients_seafood(self) -> List[str]:
        return [
            "anchovies",
            "anchovy essence",
            "Arbroath smokie",
            "blachan",
            "black bream",
            "bonito",
            "brill",
            "brown shrimp",
            "catfish",
            "caviar",
            "clams",
            "cockles",
            "cod",
            "cod roe",
            "coley",
            "crab",
            "crayfish",
            "cuttlefish",
            "dab",
            "Dover sole",
            "eel",
            "fish",
            "fish burger",
            "fish cake",
            "fish goujons",
            "fish paste",
            "fish roe",
            "fish sauce",
            "fish soup",
            "flatfish",
            "flying fish",
            "fresh tuna",
            "grey mullet",
            "gurnard",
            "haddock",
            "hake",
            "halibut",
            "herring",
            "hoki",
            "John Dory",
            "king prawn",
            "kipper",
            "langoustine",
            "lemon sole",
            "ling",
            "lobster",
            "mackerel",
            "megrim",
            "mixed fish",
            "monkfish",
            "mussels",
            "octopus",
            "oily fish",
            "oyster",
            "oyster sauce",
            "perch",
            "pike",
            "plaice",
            "pollack",
            "pollock",
            "prawn",
            "prawn crackers",
            "rainbow trout",
            "red mullet",
            "red snapper",
            "salmon",
            "salt cod",
            "sardine",
            "scallop",
            "scampi",
            "sea bass",
            "sea bream",
            "sea trout",
            "seafood",
            "shellfish",
            "shrimp",
            "skate",
            "squid",
            "smoked fish",
            "smoked haddock",
            "smoked mackerel",
            "smoked salmon",
            "smoked trout",
            "snapper",
            "sole",
            "sprats",
            "squid",
            "swordfish",
            "tiger prawn",
            "tilapia",
            "tinned tuna",
            "trout",
            "turbot",
            "whelk",
            "white fish",
            "whitebait",
            "whiting",
            "winkles",
            "Worcestershire sauce",
            "zander",
        ]

    def ingredients_nonvegan(self) -> List[str]:
        return [
            "advocaat",
            "amaretti",
            "Béchamel sauce",
            "beurre manié",
            "biscotti",
            "blini",
            "brandy butter",
            "brandy snaps",
            "bread sauce",
            "brie",
            "brioche",
            "brownie",
            "buns",
            "burrata",
            "butter",
            "buttercream icing",
            "buttermilk",
            "Caerphilly",
            "cake",
            "camembert",
            "champ",
            "Chantilly cream",
            "charlotte",
            "Cheddar",
            "cheese",
            "cheese sauce",
            "Cheshire cheese",
            "chocolate biscuit",
            "chocolate cake",
            "chocolate hazelnut spread",
            "chocolate mousse",
            "chocolate truffle",
            "choux pastry",
            "Christmas cake",
            "clarified butter",
            "clotted cream",
            "coleslaw",
            "comté",
            "condensed milk",
            "cookies",
            "cottage cheese",
            "cream",
            "cream cheese",
            "cream liqueur",
            "crème fraiche",
            "crêpe",
            "croissant",
            "cupcakes",
            "curd cheese",
            "custard",
            "custard powder",
            "Danish blue",
            "dolcelette"
            "double cream",
            "double Gloucester",
            "dulce de leche",
            "edam",
            "egg",
            "egg wash",
            "egg white",
            "egg yolk",
            "emmental",
            "evaporated milk",
            "feta",
            "fondue",
            "fontina cheese",
            "frangipane",
            "fromage frais",
            "fruit cake",
            "fudge",
            "garlic and herb cream cheese",
            "ghee",
            "gingerbread",
            "goat curd",
            "goat's cheese",
            "goat's milk",
            "gorgonzola",
            "gouda",
            "gratin",
            "gruyère",
            "halloumi",
            "hollandaise sauce",
            "honey",
            "horseradish sauce",
            "hot cross buns",
            "ice cream",
            "kefir",
            "kewpie mayonnaise",
            "labneh",
            "Lancashire cheese",
            "lemon curd",
            "macaron",
            "madeira cake",
            "madeleines",
            "manchego",
            "mascarpone",
            "mayonnaise",
            "meringue",
            "milk",
            "milk chocolate",
            "milkshake",
            "mozzarella",
            "muffins",
            "nougat",
            "pancakes",
            "paneer",
            "panettone",
            "paratha",
            "parmesan",
            "pecorino",
            "potato salad",
            "quail's egg",
            "quark",
            "queso blanco",
            "raita",
            "ratafia biscuits",
            "red Leicester",
            "rice pudding",
            "ricotta",
            "roquefort",
            "royal icing",
            "salad cream",
            "scamorza",
            "sheep curd",
            "shortbread",
            "single cream",
            "smoked cheese",
            "soufflé",
            "soured cream",
            "sponge cake",
            "sponge fingers",
            "stilton",
            "Swiss roll/roulade",
            "talleggio",
            "tartare sauce",
            "toffee",
            "trifle",
            "vacherin",
            "waffles",
            "Wensleydale",
            "whipping cream",
            "white chocolate",
            "yoghurt",
            "Yorkshire pudding",
        ]

    @property
    def custom_ingrdients_to_include(self) -> List[str]:
        return sorted(self.archipelago_options.archipelagourmet_custom_ingredients_to_include.value)

    def ingredients_to_exclude(self) -> Set[str]:
        return {ingredient.lower() for ingredient in self.archipelago_options.archipelagourmet_ingredients_to_exclude.value}

    def ingredients(self) -> List[str]:
        ingredients: List[str] = list()
        ingredients_to_exclude = self.ingredients_to_exclude

        for ingredient in self.ingredients_base:
            if ingredient.lower() not in ingredients_to_exclude:
                ingredients.append(ingredient)

        if self.include_red_meat_ingredients:
            for ingredient in self.ingredients_red_meat:
                if ingredient.lower() not in ingredients_to_exclude:
                    ingredients.append(ingredient)

        if self.include_poultry_ingredients:
            for ingredient in self.ingredients_poultry:
                if ingredient.lower() not in ingredients_to_exclude:
                    ingredients.append(ingredient)

        if self.include_seafood_ingredients:
            for ingredient in self.ingredients_seafood:
                if ingredient.lower() not in ingredients_to_exclude:
                    ingredients.append(ingredient)

        if self.include_nonvegan_ingredients:
            for ingredient in self.ingredients_nonvegan:
                if ingredient.lower() not in ingredients_to_exclude:
                    ingredients.append(ingredient)

        if self.custom_ingrdients_to_include:
            for ingredient in self.custom_ingrdients_to_include:
                if ingredient.lower() not in ingredients_to_exclude:
                    ingredients.append(ingredient)

        return sorted(ingredients)

# Archipelago Options
class ArchipelagourmetRecipes(OptionList):
    """
    Indicates which recipes the player could make.
    The player is free to add or remove any options they like. Multiple appearances will function as weightings for the options provided.
    """
    display_name = "Archipelagourmet Recipes"
    default = [
        "Spaghetti Carbonara",
        "Chicken Tikka Masala",
        "Beef Stroganoff",
        "Vegetable Stir Fry",
    ]

class ArchipelagourmetTakeawayOptions(OptionList):
    """
    Indicates which takeaway options the player could order.
    The player is free to add or remove any options they like. Multiple appearances will function as weightings for the options provided.
    """
    display_name = "Archipelagourmet Takeaway Options"
    default = [
        "African",
        "American",
        "BBQ",
        "Brazilian",
        "Burgers",
        "Caribbean",
        "Chinese",
        "Ethiopian",
        "Filipino",
        "Fish and Chips",
        "French",
        "Fried Chicken",
        "Greek",
        "Indian",
        "Indonesian",
        "Italian",
        "Japanese",
        "Korean",
        "Lebanese",
        "Malaysian",
        "Mediterranean",
        "Mexican",
        "Middle Eastern",
        "Peruvian",
        "Pizza",
        "Sandwiches",
        "Spanish",
        "Sushi",
        "Tacos",
        "Thai",
        "Turkish",
        "Vietnamese"
    ]

class ArchipelagourmetRestaurantOptions(OptionList):
    """
    Indicates which restaurant options the player could order.
    The player is free to add or remove any options they like. Multiple appearances will function as weightings for the options provided.
    """
    display_name = "Archipelagourmet Restaurant Options"
    default = [
        "Burger King",
        "Costa Coffee",
        "Domino's Pizza",
        "Five Guys",
        "Greggs",
        "KFC",
        "Leon",
        "McDonald's",
        "Nando's",
        "Papa John's",
        "Pizza Express",
        "Pizza Hut",
        "Pret a Manger",
        "Starbucks",
        "Subway",
        "Taco Bell",
        "Tim Hortons",
        "Wagamama",
        "Wasabi",
        "Wetherspoon"
    ]

class ArchipelagourmetRecipesWeight(Range):
    """
    The weighting for recipes you have to make yourself (0-100).
    """
    display_name = "Archipelagourmet Recipes Weight"
    default = 25
    range_start = 0
    range_end = 100

class ArchipelagourmetTakeawayOptionsWeight(Range):
    """
    The weighting for takeaway options (0-100).
    """
    display_name = "Archipelagourmet Takeaway Options Weight"
    default = 3
    range_start = 0
    range_end = 100

class ArchipelagourmetRestaurantOptionsWeight(Range):
    """
    The weighting for restaurant options (0-100).
    """
    display_name = "Archipelagourmet Restaurant Options Weight"
    default = 2
    range_start = 0
    range_end = 100

class ArchipelagourmetIngredientsOptionsWeight(Range):
    """
    The weighting for given ingredient options (0-100).
    """
    display_name = "Archipelagourmet Ingredient Options Weight"
    default = 15
    range_start = 0
    range_end = 100

class ArchipelagourmetIngredientsIncludeRedMeatOptions(DefaultOnToggle):
    """
    Indicates whether to include red meat options in the game.
    """
    display_name = "Include Red Meat Options"

class ArchipelagourmetIngredientsIncludePoultryOptions(DefaultOnToggle):
    """
    Indicates whether to include poultry options in the game.
    """
    display_name = "Include Poultry Options"

class ArchipelagourmetIngredientsIncludeSeafoodOptions(DefaultOnToggle):
    """
    Indicates whether to include seafood options in the game.
    """
    display_name = "Include Seafood Options"

class ArchipelagourmetIngredientsIncludeNonVeganOptions(DefaultOnToggle):
    """
    Indicates whether to include non-vegan (non-meat) options in the game.
    """
    display_name = "Include Non-Vegan (Non-Meat) Options"

class ArchipelagourmetCustomIngredientsToInclude(OptionList):
    """
    Custom ingredients that should be added to meal generation.
    This can include duplicates and existing ingredients. Multiple appearances will function as weightings for the options provided.
    Exclusion takes precedence over inclusion.
    """
    display_name = "Archipelagourmet Custom Ingredients to Include"

class ArchipelagourmetIngredientsToExclude(OptionList):
    """
    Ingredients that should be excluded from meal generation.
    """
    display_name = "Archipelagourmet Ingredients to Exclude"

class ArchipelagourmetMinimumIngredientCount(Range):
    """
    The minimum number of ingredients to include when generating ingredient challenges (1-5).
    """
    display_name = "Archipelagourmet Minimum Ingredient Count"
    default = 2
    range_start = 1
    range_end = 5
    
class ArchipelagourmetMaximumIngredientCount(Range):
    """
    The maximum number of ingredients to include when generating ingredient challenges (1-5).
    """
    display_name = "Archipelagourmet Maximum Ingredient Count"
    default = 4
    range_start = 1
    range_end = 5